name: Latest YouTube Videos
on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Update latest youTube videos'
        # Default value if no value is explicitly provided
        default: 'Start'
        # Input has to be provided for the workflow to run
        required: true
jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC4Qfhlq1Xw5j6tAJ0VeoCyQ"
